# Generated by Django 3.2.3 on 2021-06-18 11:06

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='emailová adresa')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='celé jméno')),
                ('phone', models.CharField(blank=True, help_text='9 místné číslo bez předvolby', max_length=9, verbose_name='telefonní číslo')),
                ('role', models.CharField(choices=[('STUDENT', 'student'), ('TEACHER', 'Vedoucí'), ('COORDINATOR', 'Koordinátor')], default='STUDENT', max_length=30)),
                ('photo', models.ImageField(blank=True, help_text='minimální rozměr 200x200 px', upload_to=users.models.photo_directory_path, verbose_name='fotografie')),
                ('is_staff', models.BooleanField(default=False, verbose_name='správce')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='supersprávce')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivní')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='poslední přihlášení')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='catalog.organization', verbose_name='organizace')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Uživatel',
                'verbose_name_plural': 'Uživatelé',
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
