# Generated by Django 3.2 on 2021-04-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'student'), ('TEACHER', 'Vedoucí'), ('COORDINATOR', 'Koordinátor')], default='STUDENT', max_length=30),
        ),
    ]
