# Generated by Django 3.2.4 on 2021-07-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Vedoucí'), ('COORDINATOR', 'Koordinátor')], default='STUDENT', max_length=30),
        ),
    ]
