# Generated by Django 3.2.4 on 2021-08-03 11:48

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to=users.models.photo_directory_path, verbose_name='fotografie'),
        ),
    ]
