# Generated by Django 3.2.3 on 2021-06-18 11:06

import autoslug.fields
import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='název')),
                ('age_from', models.PositiveIntegerField(verbose_name='od věku')),
                ('age_to', models.PositiveIntegerField(verbose_name='do věku')),
            ],
            options={
                'verbose_name': 'Věková kategorie',
                'verbose_name_plural': 'Věkové kategorie',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='název')),
                ('url', models.URLField(help_text='např. https://vyberaktivitu.online', max_length=35, verbose_name='URL')),
                ('slug', models.SlugField(max_length=30, verbose_name='slug')),
                ('company_id', models.CharField(max_length=8, verbose_name='IČ')),
                ('vat_id', models.CharField(blank=True, max_length=10, verbose_name='DIČ')),
                ('address', models.CharField(max_length=100, verbose_name='adresa')),
                ('town', models.CharField(max_length=40, verbose_name='město')),
                ('zip_code', models.CharField(max_length=5, verbose_name='PSČ')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
            ],
            options={
                'verbose_name': 'Organizace',
                'verbose_name_plural': 'Organizace',
            },
        ),
        migrations.CreateModel(
            name='WeekSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('hour', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(22)])),
            ],
            options={
                'verbose_name': 'Týdenní rozvrh',
                'verbose_name_plural': 'Týdenní rozvrh',
                'ordering': ['hour', 'day_of_week'],
                'unique_together': {('day_of_week', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='název')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='popis')),
                ('url', models.URLField(blank=True, help_text='např. https://vyberaktivitu.online', max_length=500, verbose_name='URL')),
                ('category', models.CharField(choices=[('OTHER', 'Ostatní'), ('LANG', 'Jazykové'), ('MUSIC', 'Hudební'), ('ART', 'Umělecké'), ('SPORT', 'Sportovní')], default='OTHER', max_length=5, verbose_name='Kategorie')),
                ('image', models.ImageField(help_text='minimální rozměr 500x500 px', upload_to=catalog.models.image_directory_path, verbose_name='obrázek')),
                ('price', models.PositiveIntegerField(verbose_name='cena za kurz')),
                ('hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='počet hodin')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='maximální kapacita')),
                ('status', models.CharField(choices=[('DRAFT', 'Ke schválení'), ('PUBLISHED', 'Publikováno'), ('FINISHED', 'Ukončeno')], default='DRAFT', max_length=9, verbose_name='stav')),
                ('date_from', models.DateTimeField(help_text='Kliknutím se otevře kalendář', verbose_name='Datum začátku')),
                ('date_to', models.DateTimeField(verbose_name='Datum konce')),
                ('is_oneoff', models.BooleanField(default=False, verbose_name='Je jednodenní')),
                ('is_ad', models.BooleanField(default=False, verbose_name='Je topováno')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('age_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='catalog.agecategory', verbose_name='věková kategorie')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='catalog.organization', verbose_name='organizace')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Aktivita',
                'verbose_name_plural': 'Aktivity',
                'ordering': ['-date_modified'],
            },
        ),
    ]
