# Generated by Django 3.1.7 on 2021-03-30 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='vedoucí'),
        ),
        migrations.AddField(
            model_name='course',
            name='topic',
            field=models.ManyToManyField(to='catalog.Topic', verbose_name='zaměření'),
        ),
    ]
