# Generated by Django 3.2.3 on 2021-06-18 13:37
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        UnaccentExtension(),
    ]
