# Generated by Django 3.1.7 on 2021-04-05 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210330_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Od'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='date_to',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Do'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='maximální kapacita'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(verbose_name='cena za kurz'),
        ),
    ]
