# Generated by Django 3.1.7 on 2021-03-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210306_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='agecategory',
            name='age_from',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='agecategory',
            name='age_to',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='organization',
            name='company_id',
            field=models.CharField(max_length=8, unique=True, verbose_name='IČO'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='název organizace'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='vat_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='DIČ'),
        ),
    ]
