# Generated by Django 3.2.4 on 2021-06-23 18:58

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('catalog', '0003_auto_20210618_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='oddělujte čárkami např.: angličtina, jazyk, doučování', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
