# Generated by Django 3.1.7 on 2021-04-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210405_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_from',
            field=models.DateField(verbose_name='Od'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_to',
            field=models.DateField(verbose_name='Do'),
        ),
    ]
