# Generated by Django 3.2.4 on 2021-07-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='url',
            field=models.URLField(help_text='např. https://vyberaktivitu.online', verbose_name='URL'),
        ),
    ]
