# Generated by Django 3.1.7 on 2021-03-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210307_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(default='empty', max_length=100, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
