# Generated by Django 3.1.7 on 2021-04-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210406_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_from',
            field=models.DateTimeField(verbose_name='Od'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_to',
            field=models.DateTimeField(verbose_name='Do'),
        ),
    ]
