# Generated by Django 3.2.4 on 2021-07-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_organization_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='název'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
    ]
