# Generated by Django 3.2 on 2021-04-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210406_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_from',
            field=models.DateTimeField(verbose_name='Od data'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_to',
            field=models.DateTimeField(verbose_name='Do data'),
        ),
    ]
