# Generated by Django 3.1.7 on 2021-03-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_organization_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='company_id',
            field=models.CharField(max_length=8, verbose_name='IČO'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='vat_id',
            field=models.CharField(max_length=10, verbose_name='DIČ'),
        ),
    ]
