# Generated by Django 3.2 on 2021-04-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210408_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_oneoff',
            field=models.BooleanField(default=False, verbose_name='Je jednodenní'),
        ),
    ]
