# Generated by Django 3.2.4 on 2021-07-31 08:17

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210728_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to=catalog.models.image_directory_path, verbose_name='obrázek'),
        ),
    ]
