# Generated by Django 3.2 on 2021-04-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_course_is_oneoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Ke schválení'), ('PUBLISHED', 'Publikováno')], default='DRAFT', max_length=9, verbose_name='stav'),
        ),
    ]
