# Generated by Django 3.2.4 on 2021-08-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_course_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-date_from'], 'verbose_name': 'Aktivita', 'verbose_name_plural': 'Aktivity'},
        ),
    ]
