# Generated by Django 3.2 on 2021-04-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_course_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Aktivita', 'verbose_name_plural': 'Aktivity'},
        ),
    ]
