# Generated by Django 3.1.7 on 2021-03-10 18:16

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210310_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
