# Generated by Django 3.2 on 2021-04-12 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_course_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'pondělí'), ('TUE', 'úterý'), ('WED', 'středa'), ('THU', 'čtvrtek'), ('FRI', 'pátek'), ('SAT', 'sobota'), ('SUN', 'neděle')], default='MON', max_length=3)),
                ('hour', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(24)])),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='week_schedule',
            field=models.ManyToManyField(to='catalog.WeekSchedule', verbose_name='týdenní rozvrh'),
        ),
    ]
