# Generated by Django 3.2 on 2021-04-14 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210412_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekschedule',
            options={'ordering': ['day_of_week', 'hour'], 'verbose_name': 'Týdenní rozvrh', 'verbose_name_plural': 'Týdenní rozvrhy'},
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='hour',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AlterUniqueTogether(
            name='weekschedule',
            unique_together={('day_of_week', 'hour')},
        ),
    ]
