# Generated by Django 3.2 on 2021-04-14 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20210414_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekschedule',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
