# Generated by Django 3.2 on 2021-04-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_weekschedule_day_of_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekschedule',
            options={'ordering': ['hour', 'day_of_week'], 'verbose_name': 'Týdenní rozvrh', 'verbose_name_plural': 'Týdenní rozvrh'},
        ),
        migrations.AlterField(
            model_name='course',
            name='date_from',
            field=models.DateTimeField(help_text='Kliknutím se otevře kalendář', verbose_name='Datum začátku'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_to',
            field=models.DateTimeField(verbose_name='Datum konce'),
        ),
        migrations.AlterField(
            model_name='course',
            name='week_schedule',
            field=models.ManyToManyField(blank=True, to='catalog.WeekSchedule', verbose_name='týdenní rozvrh'),
        ),
    ]
