# Generated by Django 3.1.7 on 2021-03-11 15:26

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20210311_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='kapacita'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='upraveno'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='popis'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.PositiveIntegerField(verbose_name='počet hodin'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d', verbose_name='obrázek'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(verbose_name='cena'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, verbose_name='název'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno'),
        ),
    ]
