# Generated by Django 3.1.7 on 2021-03-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20210311_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organizace', 'verbose_name_plural': 'Organizace'},
        ),
    ]
