# Generated by Django 3.2 on 2021-04-20 05:59

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20210415_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='počet hodin'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to=catalog.models.image_directory_path, verbose_name='obrázek'),
        ),
    ]
