# Generated by Django 3.2 on 2021-04-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.ManyToManyField(related_name='courses', to='catalog.Topic', verbose_name='zaměření'),
        ),
        migrations.AlterField(
            model_name='course',
            name='week_schedule',
            field=models.ManyToManyField(blank=True, related_name='courses', to='catalog.WeekSchedule', verbose_name='týdenní rozvrh'),
        ),
    ]
