# Generated by Django 3.1.7 on 2021-03-11 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0016_auto_20210311_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='age_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='catalog.agecategory', verbose_name='věková kategorie'),
        ),
        migrations.AlterField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='catalog.organization', verbose_name='organizace'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='učitel'),
        ),
    ]
