# Generated by Django 3.1.7 on 2021-03-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20210311_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.ManyToManyField(to='catalog.Topic', verbose_name='zaměření'),
        ),
    ]
