# Generated by Django 3.2 on 2021-04-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_organization_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='company_id',
            field=models.CharField(max_length=8, verbose_name='IČ'),
        ),
    ]
