# Generated by Django 3.1.7 on 2021-03-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20210315_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Ke schválení'), ('published', 'Publikováno')], default='draft', max_length=10, verbose_name='stav'),
        ),
    ]
