# Generated by Django 3.2 on 2021-04-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_topic_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('MUSIC', 'Hudební'), ('ART', 'Umělecké'), ('LANG', 'Jazykové'), ('SPORT', 'Sportovní'), ('OTHER', 'Ostatní')], default='OTHER', max_length=5, verbose_name='Kategorie'),
        ),
    ]
