# Generated by Django 3.1.7 on 2021-03-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20210315_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='url',
            field=models.URLField(blank=True, verbose_name='webová stránka'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='vat_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='DIČ'),
        ),
    ]
