# Generated by Django 3.2 on 2021-04-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20210428_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('OTHER', 'Ostatní'), ('LANG', 'Jazykové'), ('MUSIC', 'Hudební'), ('ART', 'Umělecké'), ('SPORT', 'Sportovní')], default='OTHER', max_length=5, verbose_name='Kategorie'),
        ),
    ]
