# Generated by Django 3.2 on 2021-05-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_ad',
            field=models.BooleanField(default=False, verbose_name='Je topováno'),
        ),
    ]
