# Generated by Django 3.2 on 2021-05-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_course_is_ad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Tag',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tagy'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='topic',
        ),
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.ManyToManyField(related_name='courses', to='catalog.Tag', verbose_name='tagy'),
        ),
    ]
