# Generated by Django 3.2 on 2021-05-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_course_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
