# Generated by Django 3.2 on 2021-05-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20210511_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True, help_text='např. https://vyberaktivitu.online', max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='url',
            field=models.URLField(help_text='např. https://vyberaktivitu.online', max_length=35, verbose_name='URL'),
        ),
    ]
