# Generated by Django 3.2.4 on 2021-07-07 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='klíč')),
                ('invited_email', models.EmailField(max_length=40, unique=True, verbose_name='e-mailová adresa')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='přijata')),
                ('date_sent', models.DateTimeField(null=True, verbose_name='odeslána')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='vytvořena')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='users.coordinator', verbose_name='vytvořil')),
            ],
            options={
                'verbose_name': 'Pozvánka',
                'verbose_name_plural': 'Pozvánky',
            },
        ),
    ]
